language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t taha/docker-react -f Dockerfile.dev .
    
script:
    - docker run -e CI=true tahaarslan/docker-react npm run test